<a id='top'></a>
<h1 style='text-align:center'>Numpy Exercises 2</h1>

### Exercises

1. [Find the most frequent value in an array](#1)
2. [Find the number of rows and columns of a given array](#2)
3. [Save a given array to a text file and load it](#3)
4. [Test whether any of the elements of a given array is non-zero](#4)
5. [Test whether none of the elements of a given array is zero](#5)
6. [Create two arrays of size bigger and smaller than a given array](#6)
7. [Create an array that represents the rank of each item of a given array](#7)
8. [Count number of occurrences of each value in a given array of non-negative integers](#8)
9. [Count the number of specified character in a given array](#9)
10. [Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10](#10)

<a id='1'></a>
### 1. Find the most frequent value in an array
[Back to top](#top)

In [6]:
import numpy as np

arr = np.random.randint(1,11,size=(5,5))
print('Sample Array:\n',arr)
vals, counts = np.unique(arr, return_counts=True)
print('\nUnique Values in the array:',vals)
print('\nCounts:',counts)
print('\nReturn the index of largest value in count: ',np.argmax(counts))
print('\nMost frequent value in the array:',vals[np.argmax(counts)])

Sample Array:
 [[5 5 2 4 6]
 [1 8 4 1 1]
 [1 4 8 1 5]
 [5 6 4 6 3]
 [4 3 1 8 6]]

Unique Values in the array: [1 2 3 4 5 6 8]

Counts: [6 1 2 5 4 4 3]

Return the index of largest value in count:  0

Most frequent value in the array: 1


<a id='2'></a>
### 2. Find the number of rows and columns of a given array
[Back to top](#top)

In [37]:
arr1 = np.random.randint(1,10,size=(3,5))
print('Sample Array:\n',arr)
print('\nUsing shape: ',arr.shape)
print('Using size (rows): ',np.size(arr,axis=0))
print('Using size (columns): ',np.size(arr,axis=1))



Sample Array:
 [[8 7 9 7 2]
 [2 8 4 8 6]
 [4 3 2 7 9]]

Using shape:  (3, 5)
Using size (rows):  3
Using size (columns):  5


<a id='3'></a>
### 3. Save a given array to a text file and load it.
[Back to top](#top)

In [48]:
import numpy as np
import os
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header,delimiter=',') 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt',delimiter=',')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


<a id='4'></a>
### 4. Test whether any of the elements of a given array is non-zero.
[Back to top](#top)

In [7]:
x = np.array([1, 0, 0, 0])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))
x = np.array([0, 0, 0, 0])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))

Original array:
[1 0 0 0]
Test whether any of the elements of a given array is non-zero:
True
Original array:
[0 0 0 0]
Test whether any of the elements of a given array is non-zero:
False


<a id='5'></a>
### 5. Test whether none of the elements of a given array is zero
[Back to top](#top)

In [8]:
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[0 0 0 0]
Test if none of the elements of the said array is zero:
False
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


<a id='6'></a>
### 6. Create two arrays of size bigger and smaller than a given array
[Back to top](#top)

In [9]:
x = np.arange(16).reshape(4,4)
print("Original arrays:")
print(x)
print("\nArray with size 2x2 from the said array:")
new_array1 = np.resize(x,(2,2))
print(new_array1)
print("\nArray with size 6x6 from the said array:")
new_array2 = np.resize(x,(6,6))
print(new_array2)

Original arrays:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Array with size 2x2 from the said array:
[[0 1]
 [2 3]]

Array with size 6x6 from the said array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15  0  1]
 [ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]
 [14 15  0  1  2  3]]


<a id='7'></a>
### 7. Create an array that represents the rank of each item of a given array.
[Back to top](#top)

In [27]:
array = np.array([24, 27, 30, 29, 18, 14])
print("Original array:")
print(array)

argsort_array = array.argsort()
print('\nIndices of sorted array: ',argsort_array)

ranks_array = np.empty_like(argsort_array)
print('\nCreate array like the given array: ',ranks_array)

ranks_array[argsort_array] = np.arange(len(array))
print("\nRank of each item of the said array:")
print(ranks_array)

Original array:
[24 27 30 29 18 14]

Indices of sorted array:  [5 4 0 1 3 2]

Create array like the given array:  [5 4 0 1 3 2]

Rank of each item of the said array:
[2 3 5 4 1 0]


<a id='8'></a>
### 8. Count number of occurrences of each value in a given array of non-negative integers.
[Back to top](#top)

In [29]:
array1 = [0, 1, 6, 1, 4, 1, 2, 2, 7] 
print("Original array:")
print(array1)
print("Number of occurrences of each value in array: ")
print(np.bincount(array1))

Original array:
[0, 1, 6, 1, 4, 1, 2, 2, 7]
Number of occurrences of each value in array: 
[1 3 2 0 1 0 1 1]


<a id='9'></a>
### 9. Count the number of specified character in a given array
[Back to top](#top)

In [30]:
x1 = np.array(['Python', 'PHP', 'JS', 'examples', 'html'], dtype=np.str)
print("\nOriginal Array:")
print(x1)
print("Number of ‘P’:")
r = np.char.count(x1, "P")
print(r)


Original Array:
['Python' 'PHP' 'JS' 'examples' 'html']
Number of ‘P’:
[1 2 0 0 0]


<a id='10'></a>
### 10.  Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
[Back to top](#top)

In [32]:
print("Creating 5X2 array using numpy.arange")
sampleArray = np.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]
