<a id='top'></a>
<h1 style='text-align:center'>Numpy Basics</h1>

### Contents

* [Initializing Numpy Array](#initialize)<br>
* [Set the data type of the element](#datatype)<br>
* [Returns the shape of the array](#shape)<br>
* [Initializing range of elements](#range)<br>
* [Reshaping Array](#reshape)<br>
* [size,itemsize and ndim](#size)<br>
* [creating array](#create)<br>
* [Indexing and Slicing](#slice)<br>
* [Iterating over Array](#iterate)<br>
* [Joining Arrays](#join)<br>
* [Splitting Arrays](#split)<br>
* [Append,Insert and Delete Elements](#append)<br>
* [Copy and Views](#copy)<br>

<a id='initialize'></a>
### Initializing Numpy Array
[Back to top](#top)

In [4]:
import numpy as np

#One dimensional
arr1 = np.array([1,2,3])
#Two dimensional
arr2 = np.array([[1,2,3],[4,5,6]])
#Three dimensional
arr3 = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])

print('\nOne dimension:')
print(arr1)
print('\nTwo dimension:')
print(arr2)
print('\nThree dimension:')
print(arr3)


One dimension:
[1 2 3]

Two dimension:
[[1 2 3]
 [4 5 6]]

Three dimension:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


<a id='datatype'></a>
### Set the data type of the element
[Back to top](#top)

In [64]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc.

arr1 = np.array([1,2,3],dtype='int16')
arr2 = np.array([1,2,3],dtype=np.int16)
print(arr1.dtype)
print(arr2.dtype)

arr3 = np.array([('owen',20),('mark',19)],dtype=np.dtype([('name','S20'),('age','int16')]))
print(arr3)

int16
int16
[(b'owen', 20) (b'mark', 19)]


<a id='shape'></a>
### Returns the shape of the array
[Back to top](#top)

In [66]:
#One dimensional
arr1 = np.array([1,2,3])
#Two dimensional
arr2 = np.array([[1,2,3],[4,5,6]])
#Three dimensional
arr3 = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(3,)
(2, 3)
(2, 2, 3)


<a id='range'></a>
### Initializing range of elements
[Back to top](#top)

In [63]:
#range in plain python
arr1 = range(20)
print('Python List')
print([i for i in arr1])

#range in numpy
print('\nNumpy array')
arr1 = np.arange(20)
print(arr1)
arr2 = np.arange(0,30,2)
print(arr2)

print('\nnumpy linspace')
arr3 = np.linspace(0,10,5)
print(arr3)
arr4 = np.linspace(0,10,5,endpoint=False) #stop value not included
print(arr4)
arr5 = np.linspace(0,10,5,retstep=True) #returns the step value
print(arr5)

Python List
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

Numpy array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]

numpy linspace
[ 0.   2.5  5.   7.5 10. ]
[0. 2. 4. 6. 8.]
(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)


<a id='reshape'></a>
### Reshaping Array
[Back to top](#top)

In [30]:
# using shape - does affect the original array
arr1 = np.arange(15)
arr1.shape = (3,5)
print('Using shape')
print(arr1)

#using reshape - does not affect the original array ... must be initialized in another variable

#resizing the array using reshape but with the style of shape
arr2 = np.arange(15)
arr2.reshape(3,5)
print('\nUsing reshape sample 1')
print(arr2)

arr3 = np.arange(15)
arr3 = arr3.reshape(3,5)
print('\nUsing reshape sample 2')
print(arr3)

print('\nFlatten the array')
arr4 = np.arange(15).reshape(3,5)
print(arr4.ravel())
print(arr4.flatten())

Using shape
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Using reshape sample 1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Using reshape sample 2
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Flatten the array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


<a id='size'></a>
### size,itemsize and ndim
[Back to top](#top)

In [86]:
arr1 = np.arange(15)
arr2 = np.arange(15).reshape(3,5)
arr3 = np.arange(18).reshape(2,3,3)

print('size returns the number of items regardless of dimension of the array')
print('itemsize return the number of bytes of each element in the array\n')
print('One dimensional array:\n',arr1)
print('Size: ',arr1.size)
print('Item Size: ',arr1.itemsize)
print('Dimension: ',arr1.ndim)
print('\nTwo dimensional array:\n',arr2)
print('Size: ',arr2.size)
print('Item Size: ',arr2.itemsize)
print('Dimension: ',arr2.ndim)
print('\nThree dimensional array:\n',arr3)
print('Size: ',arr3.size)
print('Item Size: ',arr3.itemsize)
print('Dimension: ',arr3.ndim)

size returns the number of items regardless of dimension of the array
itemsize return the number of bytes of each element in the array

One dimensional array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Size:  15
Item Size:  4
Dimension:  1

Two dimensional array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Size:  15
Item Size:  4
Dimension:  2

Three dimensional array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
Size:  18
Item Size:  4
Dimension:  3


<a id='create'></a>
### create arrays
[Back to top](#top)

In [5]:
arr1 = np.empty([3,3],dtype='int')
arr2 = np.zeros((3,3),dtype='int')
arr3 = np.ones((3,3),dtype='int')
arr4 = np.random.randint((10),size=(3,3))
arr5 = np.full((3,3),3)

print('empty:\n',arr1)
print('\nzeros:\n',arr2)
print('\nones:\n',arr3)
print('\nrandom:\n',arr4)
print('\nfull:\n',arr5)

empty:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

zeros:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

ones:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

random:
 [[8 8 4]
 [6 6 2]
 [2 8 7]]

full:
 [[3 3 3]
 [3 3 3]
 [3 3 3]]


<a id='slice'></a>
### Indexing and Slicing
[Back to top](#top)

In [33]:
arr1 = np.arange(24).reshape(4,6)

print('Sample Array\n',arr1)

print('\n2nd row,3rd element: ',arr1[1,2])
print('\n3rd row,2nd element and 2nd to the last element:\n',arr1[2,[1,-2]])
print('\n3rd column until end:\n',arr1[:,2:])
print('\nFirst column and last column:\n',np.transpose(np.hstack(arr1[:,[[0],[-1]]])))
print('\nElements in corners:\n',arr1[[[0],[-1]],[[0,-1],[0,-1]]])
print('\nOdd elements:\n',arr1[arr1%2!=0])


Sample Array
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

2nd row,3rd element:  8

3rd row,2nd element and 2nd to the last element:
 [13 16]

3rd column until end:
 [[ 2  3  4  5]
 [ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]]

First column and last column:
 [[ 0  5]
 [ 6 11]
 [12 17]
 [18 23]]

Elements in corners:
 [[ 0  5]
 [18 23]]

Odd elements:
 [ 1  3  5  7  9 11 13 15 17 19 21 23]


<a id='iterate'></a>
### Iterating over array
[Back to top](#top)

In [18]:
arr1 = np.arange(15).reshape(3,5)
print('Sample array:\n',arr1)
print()

for i in np.nditer(arr1): print(i,end=' ')
print()
for i in np.nditer(arr1,order='C'): print(i,end=' ')
print()
for i in np.nditer(arr1,order='F'): print(i,end=' ')

Sample array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 
0 5 10 1 6 11 2 7 12 3 8 13 4 9 14 

<a id='join'></a>
### Joining Arrays
[Back to top](#top)

In [81]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
print('Note: There could be one or more arrays in the parameter. vstack and hstack does not need to specify the axis.\n')
print('First Array:\n',arr1)
print('Second Array:\n',arr2)
print('\nConcatenate arrays in axis 0:\n',np.concatenate((arr1,arr2)))
print('\nConcatenate arrays in axis 1:\n',np.concatenate((arr1,arr2),axis=1))
print('\nStacks\n')
print('stack: add a new axis\n',np.stack((arr1,arr2)))
print('\nvstack:\n',np.vstack((arr1,arr2)))
print('\nhstack:\n',np.hstack((arr1,arr2)))
arr3 = np.arange(1,13).reshape(3,4)
print('\nThird Array:\n',arr3)
print('\nconcatenate rows in third array using concatenate:\n',np.concatenate(arr3))
print('\nconcatenate rows in third array using hstack:\n',np.hstack(arr3))
print('\nJoining first and second array using append:\n',np.append(arr1,arr2))

Note: There could be one or more arrays in the parameter. vstack and hstack does not need to specify the axis.

First Array:
 [[1 2]
 [3 4]]
Second Array:
 [[5 6]
 [7 8]]

Concatenate arrays in axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenate arrays in axis 1:
 [[1 2 5 6]
 [3 4 7 8]]

Stacks

stack: add a new axis
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack:
 [[1 2 5 6]
 [3 4 7 8]]

Third Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

concatenate rows in third array using concatenate:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

concatenate rows in third array using hstack:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Joining first and second array using append:
 [1 2 3 4 5 6 7 8]


<a id='split'></a>
### Splitting Arrays
[Back to top](#top)

In [76]:
arr1 = np.arange(1,13)
print('Sample Array 1:\n',arr1)
print('\nSplitting the array into 3:\n',np.split(arr1,3))

arr2 = np.arange(1,17).reshape(4,4)
print('\nSample Array 2:\n',arr2)
print('\nSplitting the array using hsplit:\n',np.hsplit(arr2,2))
print('\nSplitting the array using vsplit:\n',np.vsplit(arr2,2))

Sample Array 1:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Splitting the array into 3:
 [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

Sample Array 2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Splitting the array using hsplit:
 [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]

Splitting the array using vsplit:
 [array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


<a id='append'></a>
### Append,Insert and Delete Elements
[Back to top](#top)

In [3]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(4)
print('Sample Array 1:\n',arr1)
print('\nSample Array 2:\n',arr2)
print('\nAppend array2 to array1:\n',np.append(arr1,arr2))
print('\nInsert array2 to array1:\n',np.insert(arr1,3,arr2))
print('\nDelete array2(as index) to array1:\n',np.delete(arr1,arr2))

arr3 = np.expand_dims(np.arange(4),axis=0)
print('\nAppend array3 to array1:\n',np.append(arr1,arr3,axis=0))
print('\nInsert array3 to array1 in row 3:\n',np.insert(arr1,2,arr3,axis=0))
print('\nDelete 2nd row of array1:\n',np.delete(arr1,1,axis=0))
print('\nDelete 2nd column of array1:\n',np.delete(arr1,1,axis=1))

Sample Array 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sample Array 2:
 [0 1 2 3]

Append array2 to array1:
 [ 1  2  3  4  5  6  7  8  9 10 11 12  0  1  2  3]

Insert array2 to array1:
 [ 1  2  3  0  1  2  3  4  5  6  7  8  9 10 11 12]

Delete array2(as index) to array1:
 [ 5  6  7  8  9 10 11 12]

Append array3 to array1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 0  1  2  3]]

Insert array3 to array1 in row 3:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 0  1  2  3]
 [ 9 10 11 12]]

Delete 2nd row of array1:
 [[ 1  2  3  4]
 [ 9 10 11 12]]

Delete 2nd column of array1:
 [[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]


<a id='copy'></a>
### Copy and Views
[Back to top](#top)

In [50]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = arr1
print('Array 1:\n',arr1)
print('\narr2 = arr1:')
print('\nArray 2:\n',arr2)
print('\nid(Array1):',id(arr1),'==','id(Array2):',id(arr2))
print('Array 1 == Array 2: ',id(arr1)==id(arr2))

Array 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

arr2 = arr1:

Array 2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

id(Array1): 1618175300672 == id(Array2): 1618175300672
Array 1 == Array 2:  True


In [65]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = arr1.view()
print('Array 1:\n',arr1)
print('\narr2 = arr1.view():')
print('\nArray 2:\n',arr2)
print('\nid(Array1):',id(arr1),'==','id(Array2):',id(arr2))
print('Array 1 == Array 2: ',id(arr1)==id(arr2))

print('\nChange in the values in the array also changes the values of the original.')
print('\narr2[0]=[10,10,10,10]')
arr2[0]=[10,10,10,10]
print('\nArray 2:\n',arr2)
print('Array 1:\n',arr1)

print('\nBut change in dimensions of the array doesn’t change dimensions of the original.')

print('\narr2.shape = (2,6)')
arr2.shape = (2,6)
print('\nArray 2:\n',arr2)
print('Array 1:\n',arr1)

Array 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

arr2 = arr1.view():

Array 2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

id(Array1): 1618175389984 == id(Array2): 1618175390864
Array 1 == Array 2:  False

Change in the values in the array also changes the values of the original.

arr2[0]=[10,10,10,10]

Array 2:
 [[10 10 10 10]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array 1:
 [[10 10 10 10]
 [ 5  6  7  8]
 [ 9 10 11 12]]

But change in dimensions of the array doesn’t change dimensions of the original.

arr2.shape = (2,6)

Array 2:
 [[10 10 10 10  5  6]
 [ 7  8  9 10 11 12]]
Array 1:
 [[10 10 10 10]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [64]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = arr1.copy()
print('Array 1:\n',arr1)
print('\narr2 = arr1.copy():')
print('\nArray 2:\n',arr2)
print('\nid(Array1):',id(arr1),'==','id(Array2):',id(arr2))
print('Array 1 == Array 2: ',id(arr1)==id(arr2))

print('\nChange in the values in the array doesn\'t changes the values of the original.')
print('\narr2[0]=[10,10,10,10]')
arr2[0]=[10,10,10,10]
print('\nArray 2:\n',arr2)
print('Array 1:\n',arr1)

print('\nChange in dimensions of the array also doesn’t change dimensions of the original.')

print('\narr2.shape = (2,6)')
arr2.shape = (2,6)
print('\nArray 2:\n',arr2)
print('Array 1:\n',arr1)

Array 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

arr2 = arr1.copy():

Array 2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

id(Array1): 1618175390864 == id(Array2): 1618175390944
Array 1 == Array 2:  False

Change in the values in the array doesn't changes the values of the original.

arr2[0]=[10,10,10,10]

Array 2:
 [[10 10 10 10]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Change in dimensions of the array also doesn’t change dimensions of the original.

arr2.shape = (2,6)

Array 2:
 [[10 10 10 10  5  6]
 [ 7  8  9 10 11 12]]
Array 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
