<a id='top'></a>
<h1 style='text-align:center'>Numpy Exercises 1</h1>

### Exercises

1. [Replace all odd numbers in arr with -1 without changing arr](#1)
2. [Convert a 1D array to a 2D array with 2 rows](#2)
3. [Create the following pattern without hardcoding](#3)
4. [From array a remove all items present in array b](#4)
5. [Get the positions where elements of a and b match](#5)
6. [Get all items between 5 and 10 from a](#6)
7. [Swap columns 1 and 2 in the array arr / swap rows 1 and 2 in the array arr](#7)
8. [Reverse the rows/columns of a 2D array arr](#8)
9. [Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10](#9)
10. [Print or show only 3 decimal places of the numpy array rand_arr](#10)

<a id='1'></a>
### 1. Replace all odd numbers in arr with -1 without changing arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

out

#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

arr

#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[Back to top](#top)

In [2]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print('Answer 1:\n')
out = arr.copy()
out[out%2==1] = -1
print(out)
print(arr)

print('\nAnswer 2:\n')
out = np.where(arr % 2 == 1, -1, arr)
print(out)
print(arr)


Answer 1:

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]

Answer 2:

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


<a id='2'></a>
### 2. Convert a 1D array to a 2D array with 2 rows

Input:

np.arange(10)

Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

[Back to top](#top)

In [26]:
arr = np.arange(10)
print(arr.reshape(2, -1))  # Setting to -1 automatically decides the number of cols

[[0 1 2 3 4]
 [5 6 7 8 9]]


<a id='3'></a>
### 3. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input :

a = np.array([1,2,3])

Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

[Back to top](#top)

In [5]:
arr = np.array([1,2,3])

a = np.repeat(arr,3)
b = np.tile(arr,3)
print(np.concatenate((a,b)))

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


<a id='4'></a>
### 4. From array a remove all items present in array b

Input:

a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

Desired Output:

array([1,2,3,4])

[Back to top](#top)

In [10]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

print(np.setdiff1d(a,b))

[1 2 3 4]


<a id='5'></a>
### 5. Get the positions where elements of a and b match

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:

#> (array([1, 3, 5, 7]),)

[Back to top](#top)

In [14]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.where(a==b))

(array([1, 3, 5, 7], dtype=int64),)


<a id='6'></a>
### 6. Get all items between 5 and 10 from a.

Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])

Desired Output:

(array([6, 9, 10]),)

[Back to top](#top)

In [30]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

print('Method 1:',a[np.where((a>=5) & (a<=10))])
print('Method 2:',a[np.logical_and(a>=5,a<=10)])

Method 1: [ 6  9 10]
Method 2: [ 6  9 10]


<a id='7'></a>
### 7. Swap columns 1 and 2 in the array arr / swap rows 1 and 2 in the array arr
[Back to top](#top)

In [68]:
arr = np.arange(9).reshape(3,3)
print('Original Array:\n',arr)
print('\nSwapped Array: columns\n',arr[:,[1,0,2]])

arr = np.arange(9).reshape(3,3)
print('\nOriginal Array:\n',arr)
print('\nSwapped Array: rows\n',arr[[1,0,2],:])

Original Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Swapped Array: columns
 [[1 0 2]
 [4 3 5]
 [7 6 8]]

Original Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Swapped Array: rows
 [[3 4 5]
 [0 1 2]
 [6 7 8]]


<a id='8'></a>
### 8. Reverse the rows/columns of a 2D array arr.
[Back to top](#top)

In [70]:
arr = np.arange(9).reshape(3,3)
print('Original Array:\n',arr)
print('\nReversed Array:\n',arr[::-1,:])

arr = np.arange(9).reshape(3,3)
print('\nOriginal Array:\n',arr)
print('\nReversed Array:\n',arr[:,::-1])

Original Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Reversed Array:
 [[6 7 8]
 [3 4 5]
 [0 1 2]]

Original Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Reversed Array:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


<a id='9'></a>
### 9. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
[Back to top](#top)

In [3]:
arr = np.arange(9).reshape(3,3)

print('Solution Method 1:')
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

print('\nSolution Method 2:')
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

Solution Method 1:
[[5.89396746 8.0803073  5.87492506]
 [8.25972234 9.09221641 8.32292428]
 [8.03775868 9.31703423 7.4667828 ]
 [9.71990975 5.76089051 8.31284133]
 [5.87722118 7.84054874 5.3679374 ]]

Solution Method 2:
[[6.52445383 5.26074249 9.24757686]
 [5.97597301 8.62434831 5.72566971]
 [5.2218547  7.42678381 7.56093416]
 [8.54785103 7.98000908 6.45325562]
 [6.36634615 7.54009102 9.07867175]]


<a id='10'></a>
### 10.  Print or show only 3 decimal places of the numpy array rand_arr.
[Back to top](#top)

In [98]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)

print(rand_arr)

[[0.932 0.518 0.968]
 [0.713 0.931 0.982]
 [0.253 0.183 0.704]
 [0.845 0.95  0.804]
 [0.97  0.912 0.577]]
